#!/bin/sh

java -jar jkonoha.jar test/array.k
java -jar jkonoha.jar test/foreach.k
java -jar jkonoha.jar test/inheri.k
java -jar jkonoha.jar test/map.k
java -jar jkonoha.jar test/str.k
java -jar jkonoha.jar test/print.k
time -p java -jar jkonoha.jar test/binarytrees.k 18
echo aobench...
time -p java -jar jkonoha.jar test/aobench.k

rm -rf *.class
rm -f ao.ppm

