/****************************************************************************
 * KONOHA ASSURANCE CASE
 *  written by Kimio Kuramitsu  twitter: @konohakun 
 ***************************************************************************/


// We need more tests for character conversion. 
//
// TODO
//assure "SupportCharacterConversion" {
//	assert charset:SJIS;   // This means we succeed to link to libiconv 
//}
//
