void gluNurbsCallback(GLUnurbs* nurb, GLenum which, GLvoid(*CallBackFunc)());
void gluQuadricCallback(GLUquadric* quad, GLenum which, GLvoid(*CallBackFunc)());
void gluTessCallback(GLUtesselator* tess, GLenum which, GLvoid(*CallBackFunc)());
void* glutStrokeRoman;
void* glutStrokeMonoRoman;
void* glutBitmap9By15;
void* glutBitmap8By13;
void* glutBitmapTimesRoman10;
void* glutBitmapTimesRoman24;
void* glutBitmapHelvetica10;
void* glutBitmapHelvetica12;
void* glutBitmapHelvetica18;
void glutWMCloseFunc(void(*func)(void));
int glutCreateMenu(void(*)(int));
void glutDisplayFunc(void(*func)(void));
void glutReshapeFunc(void(*func)(int width, int height));
void glutKeyboardFunc(void(*func)(unsigned char key, int x, int y));
void glutMouseFunc(void(*func)(int button, int state, int x, int y));
void glutMotionFunc(void(*func)(int x, int y));
void glutPassiveMotionFunc(void(*func)(int x, int y));
void glutEntryFunc(void(*func)(int state));
void glutVisibilityFunc(void(*func)(int state));
void glutIdleFunc(void(*func)(void));
void glutTimerFunc(unsigned int millis, void(*func)(int value), int value);
void glutMenuStateFunc(void(*func)(int state));
void glutSpecialFunc(void(*func)(int key, int x, int y));
void glutSpaceballMotionFunc(void(*func)(int x, int y, int z));
void glutSpaceballRotateFunc(void(*func)(int x, int y, int z));
void glutSpaceballButtonFunc(void(*func)(int button, int state));
void glutButtonBoxFunc(void(*func)(int button, int state));
void glutDialsFunc(void(*func)(int dial, int value));
void glutTabletMotionFunc(void(*func)(int x, int y));
void glutTabletButtonFunc(void(*func)(int button, int state, int x, int y));
void glutMenuStatusFunc(void(*func)(int status, int x, int y));
void glutOverlayDisplayFunc(void(*func)(void));
void glutWindowStatusFunc(void(*func)(int state));
void glutKeyboardUpFunc(void(*func)(unsigned char key, int x, int y));
void glutSpecialUpFunc(void(*func)(int key, int x, int y));
void glutJoystickFunc(void(*func)(unsigned int buttonMask, int x, int y, int z), int pollInterval);
