int f(int[] a) {
    int n = 0;
    for (int i = 0; i < a.size; i++) {
        n += i;
    }
    return n;
}
//int g() {
//    int n = 0;
//    String x = "a";
//    for (int i = 0; i < 10; i++) {
//        System.setProperty("x", f(i));
//    }
//    OUT.println(x);
//    return 10;
//}
void main (String[] args) {
    Int[] a = [0, 0, 0, 0, 0];
    String s = "abcde";
    Bytes  b = (to Bytes) s;
    f(a);
    print a.size;
    print s.size;
    print b.size;
}
