/****************************************************************************
 * KONOHA ASSURANCE CASE
 *  written by Kimio Kuramitsu  twitter: @konohakun 
 ***************************************************************************/

// Scala-style class

/**
class Person(String name, int age);

assure "DeclareScalaClass" {
	Person p1 = new Person("naruto", 17);
	assert p1.name == "naruto";
	assert p1.age == 17;
}
**/
