/****************************************************************************
 * KONOHA ASSURANCE CASE
 *  written by Kimio Kuramitsu  twitter: @konohakun 
 ***************************************************************************/

/***
int getline() {
	// In the past, line comment disturbed line counting
	n = __line__;
	print __func__, __line__;
	return n;
}

assure "UnitTest:SystemVariable" {
	n = __line__;
	print __file__, __line__;
	assert n == 10;
	assert getline() == 4;
}
**/
